base: ../../base/datasets/youtube_asl.yaml

dataset:
  source:
    stop_on_transcript_block: true
    # transcript_proxy_http: http://user:pass@host:port
    # transcript_proxy_https: http://user:pass@host:port
    max_text_length: 300
    min_duration: 0.2
    max_duration: 60.0
    text_processing:
      lowercase: false

processing:
  enabled: true
  processor: video2pose
  detection: "null"
  pose: mediapipe
  sample_rate: 0.5
  max_workers: 1
  pose_config:
    model_complexity: 1
    min_detection_confidence: 0.5
    min_tracking_confidence: 0.5
    refine_face_landmarks: true
    batch_size: 16

post_processing:
  enabled: true
  recipes:
    - normalize
  normalize:
    keypoint_preset: mediapipe_553_to_85
    mode: xy_isotropic_z_minmax
    mask_empty_frames: true

output:
  enabled: true
  type: webdataset

run_name: default

paths:
  root: dataset/youtube_asl
